// The Terms of Service shown in full at sign-up (app/terms.tsx), which the person
// must scroll to the end of before Agree turns on, and again from Settings.
// DRAFT written 2026-09-24 from how OVOA works; it needs a lawyer's review before
// launch, and every [BRACKETED] value must be filled in.
// A new wording needs a new TERMS_VERSION here and in api/src/terms.ts.

export const TERMS_VERSION = 1;
export const TERMS_UPDATED = "September 24, 2026";

export type TermsSection = { title: string; paragraphs: string[] };

export const TERMS: TermsSection[] = [
  {
    title: "1. Agreeing to these Terms",
    paragraphs: [
      "These Terms of Service (the \"Terms\") are a legal agreement between you and [COMPANY LEGAL NAME], a company formed in [STATE OF FORMATION] (\"OVOA\", \"we\" or \"us\"). They cover the OVOA iPhone app, the OVOA Band, our website at ovoa.ai, and our server at api.ovoa.ai (together, the \"Service\").",
      "By creating an account, tapping Agree, or using the Service, you agree to these Terms. If you don't agree, don't use the Service.",
      "Our Privacy Policy at [PRIVACY POLICY URL] explains what information we collect and how we use it. It's part of these Terms, and so are the separate agreements some features ask for, such as the \"AI and your data\" screen.",
      "Section 22 says that most disputes will be settled by binding individual arbitration, not in court, and that you give up the right to join a class action. You can opt out within 30 days.",
      "The law where you live may give you rights that these Terms can't take away. Nothing here limits them.",
    ],
  },
  {
    title: "2. Who can use OVOA, and your account",
    paragraphs: [
      "You must be at least 18 to use OVOA, and by using it you confirm that you are. We don't knowingly collect information from anyone under 18, and we'll close any account we learn belongs to someone under 18.",
      "You must also be able to form a binding contract, and you must not be barred from the Service by the laws that apply to you, including U.S. sanctions and export laws.",
      "You can sign up with an email address and password (the email address must be verified), with Sign in with Apple, or with Google sign-in. Apple's or Google's terms also apply when you sign in with them.",
      "Give us accurate information, and keep your email address up to date; that's where we send important notices.",
      "Each account is for one person. Don't share, sell or transfer it, create accounts for others or by automated means, or open extra accounts to get around limits.",
      "Keep your password and devices secure, and use a passcode on your iPhone: anyone who can unlock it may be able to talk to OVOA as you and have it act for you. You're responsible for activity under your account unless our own failure caused it. If you think someone else has used it, tell us right away at [CONTACT EMAIL].",
    ],
  },
  {
    title: "3. What OVOA is, early access, and how it changes",
    paragraphs: [
      "OVOA is an AI personal assistant for iPhone. You talk or type to it, and it helps with everyday things, from reminders, notes and your calendar to messages, health, food, a simple picture of your money, and small personal apps like trackers.",
      "The optional OVOA Band is a clip you wear. It connects to your iPhone over Bluetooth, so you can talk to OVOA through it, feel a buzz for alarms and reminders, and share your heart rate.",
      "Health, notes and other features that don't use AI work on the Free plan. Features that use AI need a paid plan and your agreement on the \"AI and your data\" screen (see sections 4 and 8).",
      "You need a compatible iPhone and iOS version, and most features need an internet connection. Many features need permissions you grant in iOS, such as the microphone, notifications, location, contacts, calendars, Apple Health and Bluetooth; without them, those features won't work.",
      "OVOA is in early access and is distributed through Apple's TestFlight, whose terms also apply. Test builds may expire, and you may need to install a newer one. During early access, and for anything we call beta or experimental, features may be unfinished or unreliable, and may change or be removed without notice. Don't rely on them for anything important.",
      "We may add, change, limit or remove features at any time. If a change takes something important away from a paid plan, we'll try to tell you ahead of time, and you can always cancel.",
      "We don't promise that OVOA will always be available or free of errors. It depends on your iPhone, Bluetooth, your network and other companies' services, and it may stop working for a time.",
    ],
  },
  {
    title: "4. Plans, billing, cancellation and refunds",
    paragraphs: [
      "OVOA offers these plans. Prices are in U.S. dollars and, unless we say otherwise, don't include taxes, which you're responsible for.",
      "• Free: health, notes, and apps that don't use AI.",
      "• Base, $9.95 a month: every AI feature, with up to 20 AI uses a day.",
      "• Pro, $25.95 a month: the same features as Base, with about three times the daily usage (up to 60 AI uses a day).",
      "Paid plans are bought on ovoa.ai, not in the App Store. Stripe processes payments under its own terms, and we don't receive your full card number.",
      "Your plan renews automatically every month until you cancel. By subscribing, you authorize us, through Stripe, to charge your payment method the plan's price plus any taxes at the start of each monthly period. If a payment fails, we may retry it and may pause your paid features or move you to Free until it succeeds.",
      "You can cancel at any time, as described on ovoa.ai, or by emailing [CONTACT EMAIL]. Cancelling stops future renewals. You keep your plan until the end of the period you've paid for, and then your account moves to Free. Cancelling doesn't delete your account or data (see section 18), and deleting the app doesn't cancel your plan.",
      "Refunds: [REFUND POLICY — e.g. no refunds for partial months]. This doesn't limit any refund rights you have under the law where you live.",
      "We may change prices, what each plan includes, and its limits. We'll tell you about a price increase by email or in the app at least [PRICE CHANGE NOTICE PERIOD — e.g. 30 days] before it applies to you. If you don't want to pay the new price, cancel before then.",
      "If you think a charge is wrong, contact us first. If you dispute it with your bank instead, we may suspend your paid plan while the dispute is open.",
    ],
  },
  {
    title: "5. Usage limits and fair use",
    paragraphs: [
      "Base includes up to 20 AI uses a day, and Pro up to 60. In general, each request that OVOA answers with AI counts as one use, and we decide how uses are counted. Daily limits reset each day, and unused uses don't carry over.",
      "Every paid plan also has a monthly fair-use cap of [MONTHLY FAIR-USE CAP], which keeps OVOA affordable and available for everyone.",
      "When you reach a limit, AI features pause until the limit resets or you change plans, and features that don't use AI keep working. Work OVOA does in the background, such as the background agent's checks, may count toward your limits.",
      "Plans are for one person's own use. Don't use scripts, bots, or shared or multiple accounts to get more usage, and don't resell or share access. We may slow, limit or suspend use that is automated, far above normal, or looks like abuse.",
    ],
  },
  {
    title: "6. The OVOA Band",
    paragraphs: [
      "The OVOA Band is a small clip with a microphone, a button, a vibration motor and a heart-rate sensor. It connects to your iPhone over Bluetooth and needs the OVOA app. It's a one-time purchase of $89.99 and works without a paid plan, although features that use AI still need one.",
      "The Band relies on its Bluetooth connection to your iPhone. If the phone is out of range, off or low on battery, if Bluetooth is off, or if iOS limits the app in the background, the Band may not buzz, pass on what you say, or send heart-rate readings.",
      "The Band has a rechargeable battery. Charge it only as its instructions describe. Don't open, puncture, crush or heat it, and stop using it if it's damaged, swollen or unusually hot.",
      "Water and dust: [BAND WATER RESISTANCE — e.g. the Band is not waterproof or water resistant]. Unless we state a water-resistance rating for your Band, keep it dry.",
      "Stop wearing the Band if it irritates your skin. It has small parts, so keep it away from young children and pets.",
      "Returns: you may return a Band you bought from us within [BAND RETURN WINDOW — e.g. 30 days] of delivery, as described on ovoa.ai.",
      "Limited warranty: [BAND LIMITED WARRANTY — e.g. one year against defects in materials and workmanship; we repair, replace or refund]. It doesn't cover normal wear, accidents, liquid damage (unless your Band is rated for it), misuse, repairs by anyone other than us, or normal battery decline. To make a claim, contact [CONTACT EMAIL]. Apart from this warranty and any the law requires, section 19 applies to the Band.",
      "Heart-rate readings from the Band are estimates, not medical-grade (see section 11).",
    ],
  },
  {
    title: "7. AI features and their limits",
    paragraphs: [
      "Many OVOA features use artificial intelligence (AI) to understand what you ask, write replies, and decide what to do. AI is useful, but it makes mistakes:",
      "• Replies can be wrong, incomplete, out of date or inappropriate, even when they sound confident.",
      "• OVOA can mishear or misunderstand you, and it can pick the wrong contact, event, time or amount.",
      "• OVOA can occasionally say it did something when it didn't, or the reverse. If it matters, check the app, your calendar, your reminders or your sent messages.",
      "• Web search results come from sources we don't control and may be inaccurate.",
      "• Replies are made automatically, and no person reviews them before you get them. OVOA's voice is made by software.",
      "Check anything important yourself before you rely on it or act on it, especially dates, times, names, addresses, amounts, and anything about health, money, legal matters or safety. OVOA isn't a doctor, lawyer, financial adviser, therapist or other professional, and nothing it says is professional advice.",
      "You're responsible for how you use what OVOA produces, including anything you share or send to other people.",
    ],
  },
  {
    title: "8. Your agreement to AI processing, and the AI providers",
    paragraphs: [
      "OVOA's AI features work by sending information to other companies' AI systems. Before anything is sent to an AI company, the app asks for your agreement on a separate screen called \"AI and your data\". Until you agree, nothing is sent to an AI company, and features that need AI won't work.",
      "When you use an AI feature, we send what you said or typed, plus the information needed to answer it (for example, calendar entries, reminders, contacts OVOA looks up, and other details from your account that relate to your request), to these providers:",
      "• Cloudflare (Workers AI) and Z.ai, which run the GLM model that OVOA uses to write replies.",
      "• Google Gemini, as a backup when the main model isn't available, and for web searches.",
      "• Deepgram, which turns OVOA's replies into speech. Deepgram receives only the text of the reply.",
      "These providers process that information to produce a reply, under their own terms and our agreements with them. The Privacy Policy explains whether and for how long each may keep it. If we add or change providers, we'll update the Privacy Policy, and for a significant change we'll ask you to agree again in the app.",
      "You can withdraw your agreement at any time in Settings. Nothing new is then sent to AI companies and AI features stop, while features that don't use AI keep working. Withdrawing doesn't undo what was already sent, and it doesn't cancel a paid plan (see section 4).",
      "Don't put anything in a request that you don't want sent to these providers, such as passwords, card numbers, or other people's sensitive details.",
    ],
  },
  {
    title: "9. Listening, recording and the law",
    paragraphs: [
      "You choose how you start talking to OVOA:",
      "• Tap to talk in the app.",
      "• Click the button on the OVOA Band.",
      "• Say the assistant's name (the wake word).",
      "• Turn on \"Always listen\". Your iPhone then listens for the assistant's name on the device itself, and nothing is sent to us or to any AI company until the name is heard.",
      "The Band's microphone can also record your requests. Recording audio stays on your iPhone (see section 14).",
      "Listening for a name isn't perfect. OVOA may start when you didn't mean it to, such as when someone says a similar-sounding word, and treat what it hears as a request. It may also miss the name.",
      "Recording or listening to other people is regulated by law. Some U.S. states and other countries require everyone in a conversation to consent before it's recorded (all-party or two-party consent), and many places restrict recording in private spaces, at work or at school. You're solely responsible for following these laws whenever you use OVOA, including the Band and Always listen:",
      "• Tell people nearby when OVOA may be listening or recording, and get their consent when the law requires it.",
      "• Never use OVOA to secretly record, monitor or eavesdrop on anyone.",
      "• Turn off Always listen, and don't record, where it isn't allowed or appropriate.",
      "We aren't responsible for recordings you make or for how you use them.",
    ],
  },
  {
    title: "10. Actions OVOA takes for you",
    paragraphs: [
      "OVOA can do things for you, not just answer questions. Depending on your settings and the permissions you give it, OVOA can:",
      "• Set alarms and reminders, which buzz the Band or show a notification.",
      "• Keep notes, to-do lists and routines, including streaks.",
      "• Read your calendar, add events, and look up your contacts.",
      "• Prepare texts, emails and calls.",
      "• Work with your Gmail and Google Calendar, if you connect your Google account through Google's permission screen. You can disconnect it at any time.",
      "Normally, iOS shows you a prepared text or email and you tap Send yourself. These optional settings change that, and you can turn them off at any time in Settings:",
      "• \"Send texts automatically\" uses an iOS Shortcut on your own iPhone to send texts without that tap.",
      "• \"Approve for me\" lets OVOA act without asking you first, including sending emails, deleting things, and changing your contacts, calendar and reminders.",
      "• The background agent checks on things between your conversations and notifies you. At its highest setting it can also create calendar events, tasks and drafts. It never sends messages to other people or deletes anything on its own.",
      "You're responsible for everything OVOA does on your behalf and everything sent in your name, whether you tapped Send or turned on a setting that acts for you. OVOA can pick the wrong person, get details wrong, or act on something it misheard, and sent messages, deletions and changes often can't be undone. Turn on Send texts automatically or Approve for me only if you accept these risks.",
      "Only contact people who would expect to hear from you. Your carrier's charges and your email provider's rules still apply.",
    ],
  },
  {
    title: "11. Health, food and money are for information only",
    paragraphs: [
      "With your permission, OVOA can read and write Apple Health data, such as steps, sleep and heart rate, and can read your heart rate from the OVOA Band. You control this access in iOS settings. We don't use Apple Health data for advertising, and we don't sell it.",
      "OVOA is not a medical device. It doesn't diagnose, treat, cure, monitor or prevent any disease or condition. Health information and readings are for general information and wellness only, and readings can be inaccurate, late or missing.",
      "OVOA is not a substitute for a doctor. Talk to a health professional before making health decisions, and never ignore or delay medical advice because of something OVOA said. If you think you're having a medical emergency, call 911 or your local emergency number right away.",
      "Food: calorie and nutrition figures are estimates, often made by AI from how you describe a meal, and can be wrong. They aren't dietary or medical advice. If you have a health condition, an eating disorder or allergies, or you're pregnant, talk to a professional before changing what you eat.",
      "Money: OVOA keeps a simple picture of your money from numbers you type in. It doesn't connect to your bank and can't move money. What it says, such as whether a month looks tight, is general information based only on what you entered, not financial, investment, tax or legal advice.",
    ],
  },
  {
    title: "12. Safety, SOS and emergencies",
    paragraphs: [
      "OVOA includes an SOS button and lets you add emergency contacts. These can help you reach people you trust, but they have real limits:",
      "• OVOA is not a monitored emergency or medical-alert service. No one at OVOA watches for SOS alerts, and we can't send help.",
      "• OVOA does not detect falls or other emergencies.",
      "• SOS depends on your iPhone and its battery, Bluetooth, your network, your iOS settings and other companies' services, any of which can fail or be delayed. Your emergency contacts may get an alert late or not at all.",
      "In an emergency, always call 911 or your local emergency number directly. Don't wait for OVOA.",
      "Keep your emergency contacts up to date. By adding someone, you confirm that they've agreed to be your emergency contact.",
      "Alarms and reminders can fail too: the Band may be out of range or battery, notifications may be silenced, or iOS may stop the app in the background. Don't rely on OVOA alone where a missed or late alarm or reminder could cause harm, such as for medication or caring for someone.",
      "Don't use OVOA's screen while driving or doing anything else that needs your full attention.",
    ],
  },
  {
    title: "13. Your content, and the license you give us",
    paragraphs: [
      "\"Your content\" means what you give OVOA or create with it: what you say and type, recordings, notes, lists, routines, memories, named places, health, food and money entries, the personal apps you build, and the output OVOA makes for you.",
      "You own your content, and we don't claim it. As between you and us, you also own the output OVOA makes for you, to the extent anyone does. Output may not be protected by copyright, and similar output may be made for other people.",
      "You give us a worldwide, non-exclusive, royalty-free license to host, store, copy, process, transmit and display your content, and to share it with the providers described in section 8 and the Privacy Policy, only to provide, secure and support the Service for you, fix problems, and comply with the law. It ends when your content is deleted, except for copies the law requires us to keep or that remain in backups for a limited time.",
      "You're responsible for your content, and you confirm you have the rights and consents needed to give it to us, including other people's contact details, messages, and voices in recordings.",
      "Personal apps you build, such as trackers, are for your own use, and they're only as accurate as what goes into them. We may remove content that breaks these Terms or the law, but we don't have to monitor content.",
    ],
  },
  {
    title: "14. Privacy and how long we keep data",
    paragraphs: [
      "Our Privacy Policy at [PRIVACY POLICY URL] explains fully what we collect, why, who we share it with, and your rights. Here's a summary; where they differ, the Privacy Policy controls.",
      "• Most day-to-day data, such as conversation details, location points, food entries, health day records and usage details, is deleted after 14 days. We keep a short summary of each day.",
      "• Things you ask OVOA to remember, places you've named, and the words and summaries of recordings you chose to keep are kept until you delete them.",
      "• Recording audio stays on your iPhone.",
      "• The location timeline is off until you turn it on, and it needs iOS's \"Always\" location permission.",
      "• Device diagnostic logs, which don't include the contents of your messages, are kept for 7 days so we can fix problems.",
      "• You can delete memories, your chat history, and your whole account in Settings.",
      "Things OVOA adds to other services for you, such as calendar events, reminders, Apple Health entries, and emails or texts you've sent, stay there under those services' rules, even if you delete them in OVOA.",
      "We use reasonable safeguards, but no system is perfectly secure, and we can't guarantee your data will never be accessed, lost or disclosed without permission. If a breach affects your data, we'll notify you as the law requires.",
    ],
  },
  {
    title: "15. Acceptable use",
    paragraphs: [
      "Use OVOA only lawfully and as these Terms allow. Don't use it, or help anyone else use it, to:",
      "• Break any law, or violate anyone's rights, including privacy, publicity and intellectual property rights.",
      "• Harass, threaten, stalk, impersonate or intimidate anyone, or send hateful, abusive or unwanted sexual messages.",
      "• Send spam or bulk, unsolicited or automated messages or calls.",
      "• Watch, track, record or monitor anyone without their knowledge and consent, including by hiding the Band or a phone running OVOA near them.",
      "• Plan or carry out violence, fraud or scams, use OVOA's output to harm or deceive people, or use it to make decisions about people's credit, employment, housing, insurance, education or legal status.",
      "• Copy, sell, rent, sublicense or resell the Service or access to it.",
      "• Reverse engineer or decompile the app, the Band's software or our server, or try to extract their source code, models, prompts or instructions, except where the law expressly allows it.",
      "• Probe the Service for vulnerabilities, get around its security, or access accounts, data or systems that aren't yours. If you find a security problem, please tell us at [CONTACT EMAIL].",
      "• Overload the Service, or get around usage limits, plan restrictions or the \"AI and your data\" agreement, for example with multiple accounts, scripts or modified apps.",
      "• Access the Service by automated means we don't provide, or use it or its output to build a competing product or train AI models.",
      "• Break the usage rules of the companies whose services OVOA uses, including the AI providers in section 8.",
      "We may investigate misuse, remove content, limit features, suspend or close accounts, and report illegal activity to the authorities.",
    ],
  },
  {
    title: "16. Third-party services and platforms",
    paragraphs: [
      "OVOA works with services run by other companies, including:",
      "• Apple: the App Store, TestFlight, iOS and its permissions, Sign in with Apple, Apple Health, Shortcuts and notifications.",
      "• Google: Google sign-in, Gmail, Google Calendar and Gemini.",
      "• Stripe: payments for paid plans.",
      "• Cloudflare, Z.ai, Google and Deepgram: AI and voice (see section 8).",
      "These companies' own terms and privacy policies apply when you use their services. We don't control them and aren't responsible for their services, availability, security, or handling of your data. If one of them changes or stops its service, some OVOA features may stop working.",
      "OVOA's use of information received from Google APIs will follow the Google API Services User Data Policy, including its Limited Use requirements.",
      "Links in search results may lead to websites we don't control or endorse.",
    ],
  },
  {
    title: "17. Our intellectual property, and feedback",
    paragraphs: [
      "The Service, including the app, the Band's design and software, our server, and the OVOA name, logos, voice, sounds and designs (but not your content), belongs to us or our licensors and is protected by intellectual property laws.",
      "Subject to these Terms, we give you a personal, limited, non-exclusive, non-transferable, revocable license to install and use the OVOA app on iPhones you own or control, and to use the Service, for your own non-commercial use. We keep all rights we don't expressly give you. Don't use our name, logos or trademarks without our written permission. Open-source parts of the app are covered by their own licenses.",
      "If you believe something in the Service infringes your rights, contact us at [CONTACT EMAIL] with the details.",
      "If you send us ideas, suggestions or other feedback, we may use them for any purpose without paying you or owing you anything. Please don't send feedback you want kept confidential.",
    ],
  },
  {
    title: "18. Ending your account, suspension and termination",
    paragraphs: [
      "You can stop using OVOA at any time, and you can delete your account in Settings. If you have a paid plan, also make sure it's cancelled (see section 4) so you aren't charged again.",
      "We may suspend, limit or close your account if you break these Terms or the law (or we reasonably believe you have); if your use puts others, the Service or us at risk or could expose us to legal liability; if the law, a court or a platform such as Apple requires it; if you don't pay what you owe; or if we stop offering the Service or part of it. Where reasonable, we'll tell you first and give you a chance to fix the problem, unless there's a legal, safety or security reason not to.",
      "When your account is deleted, we delete or de-identify your account data in our active systems within [ACCOUNT DELETION PERIOD — e.g. 30 days]. Copies may remain in backups for a limited time until overwritten, and we may keep some information, such as payment records, where the law requires it or to resolve disputes, prevent fraud or abuse, or enforce these Terms.",
      "Deleted data can't be recovered. Data on your iPhone, including recording audio, stays there until you delete it or remove the app, and data in other services, such as your calendar or Apple Health, stays there.",
      "When your account ends, so does your right to use the Service, but anything you owe us and the sections listed in section 25 still apply.",
    ],
  },
  {
    title: "19. Disclaimer of warranties",
    paragraphs: [
      "In plain terms: we work hard on OVOA, but we can't promise that it will always work or always be right.",
      "TO THE FULLEST EXTENT THE LAW ALLOWS, THE SERVICE, INCLUDING THE APP, THE OVOA BAND (EXCEPT FOR ITS LIMITED WARRANTY IN SECTION 6), AI OUTPUT AND ALL OTHER CONTENT, IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\", WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY AND QUIET ENJOYMENT, AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING OR USAGE OF TRADE.",
      "WE DON'T WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; THAT AI OUTPUT, HEALTH READINGS, CALORIE ESTIMATES OR OTHER INFORMATION WILL BE ACCURATE, COMPLETE OR RELIABLE; THAT ALARMS, REMINDERS, NOTIFICATIONS OR SOS ALERTS WILL ARRIVE ON TIME OR AT ALL; THAT LISTENING FOR THE ASSISTANT'S NAME WILL WORK AS EXPECTED; OR THAT ACTIONS TAKEN ON YOUR BEHALF WILL BE CORRECT. YOU USE THE SERVICE AT YOUR OWN RISK.",
      "Some places don't allow certain warranties to be excluded, so some of these exclusions may not apply to you. Any warranty that can't be excluded lasts only as long as, and only to the extent that, the law requires.",
    ],
  },
  {
    title: "20. Limitation of liability",
    paragraphs: [
      "In plain terms: if something goes wrong, what we owe you is limited.",
      "TO THE FULLEST EXTENT THE LAW ALLOWS, [COMPANY LEGAL NAME] AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS AND LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL OR OPPORTUNITY, ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE, EVEN IF WE WERE TOLD SUCH DAMAGES WERE POSSIBLE.",
      "THIS INCLUDES LOSS OR HARM ARISING FROM: RELYING ON AI OUTPUT; MESSAGES, EMAILS, CALLS, DELETIONS OR CHANGES MADE ON YOUR BEHALF; MISSED OR LATE ALARMS, REMINDERS OR SOS ALERTS; RECORDINGS YOU MAKE; HEALTH, FOOD OR MONEY INFORMATION; THIRD-PARTY SERVICES; AND UNAUTHORIZED ACCESS TO YOUR ACCOUNT OR DATA.",
      "OUR TOTAL LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE WILL NOT BE MORE THAN THE GREATER OF (A) THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE 12 MONTHS BEFORE THE EVENT THAT GAVE RISE TO THE CLAIM, AND (B) $[AMOUNT].",
      "These limits apply under any legal theory, including contract, tort (including negligence) and product liability, even if a limited remedy fails of its essential purpose. They don't limit liability the law doesn't allow to be limited, such as for fraud, or for death or personal injury caused by our negligence, so some may not apply to you.",
    ],
  },
  {
    title: "21. Indemnification",
    paragraphs: [
      "To the extent the law allows, you agree to defend, indemnify and hold harmless [COMPANY LEGAL NAME] and its affiliates, officers, employees and agents from any claims, losses, liabilities, damages, costs and expenses (including reasonable attorneys' fees) arising from:",
      "• your use of the Service;",
      "• your content;",
      "• messages, emails, calls or other actions taken on your behalf;",
      "• any recording you make, or how you use it;",
      "• your breach of these Terms; or",
      "• your violation of any law or of anyone else's rights.",
      "We may take control of the defense of any such claim at our own cost, with your cooperation, and you won't settle one that affects us without our written consent. This section doesn't cover claims caused by our own negligence or misconduct.",
    ],
  },
  {
    title: "22. Disputes, arbitration and governing law",
    paragraphs: [
      "This section affects your legal rights, including your right to go to court.",
      "Talk to us first. Before starting a formal dispute, send a written notice to [CONTACT EMAIL] or [COMPANY ADDRESS] with your name, your account's email address, the problem, and what you'd like us to do. We'll do the same for a dispute with you. We'll both try in good faith to resolve it within 60 days before either of us starts arbitration or a court case.",
      "Binding arbitration. If we can't resolve it informally, you and we agree that any dispute, claim or controversy arising out of or relating to these Terms, the Service or the OVOA Band (a \"Dispute\"), including whether this agreement to arbitrate applies or can be enforced, will be resolved by binding individual arbitration, not in court. It will be administered by [ARBITRATION PROVIDER / VENUE] under its consumer rules then in effect. The Federal Arbitration Act governs this section.",
      "The arbitrator can award the same individual relief a court could, but only to the individual party bringing the claim. The arbitration will take place in the county where you live, or by phone or video, unless we both agree otherwise. Fees follow the provider's consumer rules, and where those rules or the law require, we'll pay any fees above what you'd pay to file in court.",
      "Exceptions. Either of us may bring a qualifying individual claim in small claims court, or ask a court to stop infringement or misuse of intellectual property or unauthorized access to the Service.",
      "CLASS ACTION AND JURY TRIAL WAIVER. YOU AND WE MAY BRING CLAIMS AGAINST EACH OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, COLLECTIVE, CONSOLIDATED OR REPRESENTATIVE PROCEEDING. YOU AND WE BOTH GIVE UP THE RIGHT TO A JURY TRIAL. If this waiver is found unenforceable for a particular claim, that claim alone will be decided in court.",
      "Opting out. You can opt out of arbitration by emailing [CONTACT EMAIL] or writing to [COMPANY ADDRESS] within 30 days after you first agree to these Terms, with your name, your account's email address, and a clear statement that you're opting out. The rest of these Terms still applies. If we later make a material change to this section, you can reject that change by telling us within 30 days after it takes effect.",
      "Governing law. These Terms and any Dispute are governed by the laws of the State of [GOVERNING LAW STATE] and applicable U.S. federal law, without regard to conflict-of-law rules. A Dispute that goes to court will be decided only in the state or federal courts located in [GOVERNING LAW STATE], and you and we consent to their jurisdiction. This doesn't take away protections you have under the mandatory consumer laws where you live.",
    ],
  },
  {
    title: "23. Changes to these Terms",
    paragraphs: [
      "We may update these Terms from time to time. The date at the top shows when they last changed.",
      "If we make a material change, we'll tell you ahead of time by email, in the app, or both, and we'll usually ask you to read and agree to the new Terms in the app before you continue. Agreeing again in the app means you accept the new Terms. For other changes, continuing to use OVOA after the updated Terms take effect means you accept them.",
      "If you don't agree to a change, stop using OVOA and cancel any paid plan. You can also delete your account. Changes won't apply to Disputes that arose before they took effect.",
    ],
  },
  {
    title: "24. Apple App Store terms",
    paragraphs: [
      "This section applies because the OVOA app is distributed through Apple (the App Store and TestFlight). Where it conflicts with the rest of these Terms, it controls for the app.",
      "• These Terms are between you and [COMPANY LEGAL NAME] only, not Apple. We, not Apple, are solely responsible for the app and its content.",
      "• Your license to use the app is limited to a non-transferable license to use it on Apple-branded products that you own or control, as allowed by the Usage Rules in Apple's Media Services Terms and Conditions, except that other accounts associated with you may access it through Family Sharing or volume purchasing where Apple allows.",
      "• Apple has no obligation to provide any maintenance or support for the app.",
      "• If the app fails to conform to any applicable warranty, you may notify Apple, and Apple will refund the app's purchase price to you, if any (paid plans are bought from us, not Apple). To the maximum extent the law allows, Apple has no other warranty obligation for the app, and any other claims, losses, liabilities, damages, costs or expenses caused by a failure to conform to a warranty are our responsibility, to the extent these Terms don't disclaim them.",
      "• We, not Apple, are responsible for addressing any claims by you or any third party relating to the app or your possession or use of it, including product liability claims, claims that the app fails to meet a legal or regulatory requirement, and claims under consumer protection, privacy or similar laws, including in connection with the app's use of HealthKit.",
      "• If a third party claims that the app, or your possession and use of it, infringes their intellectual property rights, we, not Apple, are solely responsible for investigating, defending, settling and discharging that claim.",
      "• You confirm that you aren't located in a country subject to a U.S. Government embargo or designated by the U.S. Government as a \"terrorist supporting\" country, and that you aren't on any U.S. Government list of prohibited or restricted parties.",
      "• Send questions, complaints or claims about the app to us (section 26).",
      "• You must follow any third-party terms that apply when you use the app, such as your mobile carrier's.",
      "• Apple and its subsidiaries are third-party beneficiaries of these Terms. Once you accept these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce them against you as a third-party beneficiary.",
    ],
  },
  {
    title: "25. General terms",
    paragraphs: [
      "Entire agreement. These Terms, the Privacy Policy, and any other agreements you accept in the app (such as \"AI and your data\") are the whole agreement between you and us about the Service, and replace any earlier ones on the same subject.",
      "Severability. If any part of these Terms is unenforceable, it will be enforced as far as the law allows, and the rest stays in effect.",
      "No waiver. Not enforcing part of these Terms doesn't mean we give up the right to enforce it later.",
      "Assignment. You may not transfer your rights or duties under these Terms without our written consent. We may transfer ours, for example in a merger, acquisition or sale of assets.",
      "Force majeure. We aren't responsible for delays or failures caused by things beyond our reasonable control, such as outages at Apple or our providers, natural disasters, war, government action, or attacks on our systems.",
      "Notices. We may send you notices by email, in the app, or by notification, and you agree to receive notices and agreements electronically. Legal notices to us must be sent to [CONTACT EMAIL] or [COMPANY ADDRESS].",
      "Relationship. You and we are independent parties; these Terms don't create a partnership, employment or agency relationship. Except for Apple (section 24) and the people protected by sections 20 and 21, no one else has rights under these Terms.",
      "Interpretation. Section titles are for convenience only, and \"including\" means \"including without limitation\". If we translate these Terms, the English version controls.",
      "Survival. Sections 4 (for amounts owed), 7, 11, 12, 13, 17 through 22, 24 and 25 continue to apply after these Terms end.",
    ],
  },
  {
    title: "26. Contact us",
    paragraphs: [
      "Questions about these Terms, a problem with OVOA, a legal notice, or an arbitration opt-out? Contact us:",
      "[COMPANY LEGAL NAME]",
      "[COMPANY ADDRESS]",
      "Email: [CONTACT EMAIL]",
      "Website: ovoa.ai",
      "If you're a California resident, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs, in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by phone at (800) 952-5210.",
    ],
  },
];
